name: Neat Starter with RSS and SEO
author: You should be here
authorUrl: https://example.com/#a-site-about-you-should-be-here
url: https://neat-starter-rss-seo.netlify.app
repo_url: https://github.com/jacebenson/neat-starter
description: A 11ty starter using netlifyCMS
twitter: yourtwitterhandleshouldbehere
icon: /static/img/apple-touch-icon.png
