name: Jace's Neat Starter
author: Jace Benson
url: https://astonishing-mousse-c43f37.netlify.app
repo_url: https://github.com/jacebenson/something
description: This is a demo description for the site
twitter: jacebenson
icon: /static/img/screenshot-2022-03-03-174427.png
