name: Jace's Neat Starter
author: Jace Benson
description: This is a demo description for the site
url: http://localhost:8080
repo_url: https://github.com/jacebenson/something
twitter: jacebenson
icon: /assets/something.png
