name: Jace's Neat Starter
author: Jace Benson
url: http://localhost:8080
repo_url: https://github.com/jacebenson/something
description: This is a demo description for the site
twitter: jacebenson
icon: /static/img/screenshot-2022-03-03-174427.png
