backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Post"
    name: "post"
    folder: "src/post"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title",             name: "title",        widget: "string" }
      - { label: "Description",       name: "description",  widget: "string" }
      - { label: "Author",            name: "author",       widget: "string"}
      - { label: "Image",             name: "image",        widget: "file" }
      - { label: "Image Alt Text",    name: "imageAltText", widget: "string" }
      - { label: "Publish Date",      name: "date",         widget: "datetime" }
      - { label: "Post code snippet", name: "prism",        widget: "boolean", default: false, required: false}
      - { label: "Body",              name: "body",         widget: "markdown" }
  - label: "Settings"
    name: "settings"
    editor:
      preview: true
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL,   name: url,  widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title,       name: title, widget: string }
              - { label: URL,         name: url,   widget: string }
              - { label: Description, name: desc,  widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name,           name: name,        widget: string }
          - { label: Author,         name: author,      widget: string }
          - { label: URL,            name: url,         widget: string }
          - { label: Repo URL,       name: repo_url,    widget: string }
          - { label: Description,    name: description, widget: string }
          - { label: Twitter handle, name: twitter,     widget: string }
          - { label: Icon,           name: icon,        widget: file}
  - label: "Pages and Partials"
    editor:
      preview: false
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/_includes/partials/content.html"
        fields:
          - { label: Body, name: body, widget: "markdown", modes: ["raw"] }
      - label: "Navbar"
        name: "navbar"
        file: "src/_includes/partials/navbar.html"
        fields:
          - { label: Body, name: body, widget: "markdown", modes: ["raw"]}
      - label: "Footer"
        name: "footer"
        file: "src/_includes/partials/footer.html"
        fields:
          - { label: Body, name: body, widget: "markdown", modes: ["raw"] }
  